export const NAME_INPUT_TEST_ID = 'input-player-name';
export const EMAIL_INPUT_TEST_ID = 'input-gravatar-email';
export const VALID_NAME = 'alguem';
export const VALID_EMAIL = 'alguem@pessoa.com';
export const INVALID_EMAIL = 'email';
/* export const VALUE_INPUT_TEST_ID = 'value-input';
export const METHOD_INPUT_TEST_ID = 'method-input';
export const TAG_INPUT_TEST_ID = 'tag-input';
export const BTN_DELETE_TEST_ID = 'delete-btn';
export const DESCRIPTION_INPUT_TEST_ID = 'description-input';
export const TOTAL_FIELD_TEST_ID = 'total-field';
export const EDIT_INPUT_TEST_ID = 'edit-btn';
export const BTN_EDIT_TEST_ID = 'edit-btn'; */
